### ISSUE TITLE
Add a prefix for website dashboard links 

### ISSUE THREAD

**Issue by Bekacru** [loglib/loglib#123]
Current Situation:
Right now, when you go to a dashboard for a website, you use a link like "loglib.io/websiteId." However, this can cause problems when we have other important links like "loglib.io/login." we disallow important links by a list of disallowed ids but It's just not the right thing to do.

Proposed Solution:
To avoid these issues, we want to change how dashboard links work. Instead of "loglib.io/websiteId," we're considering a new style like "loglib.io/[prefix]/websiteId." The prefix could be a single letter, like 's', 'w', 'a', or something else. It could also be "loglib.io/dashbaord/[prefix]/websiteId".

**Comment by Kinfe123** [comment]
Is this thing can not be fixed on middleware tho , like try to check the session when the user navigate to the dashboard with the website id which can be handled by giving a proritized if statement before other pre processes to avoid the collision between normal routes, onces logged in we can dynamically change the disallowed routes on.
